@startuml

participant 企业微信主页面 as main


participant 通讯录页面 as contact

participant 添加成员页面 as add_member
collections 添加部门弹窗 as add_department


participant 批量导入通讯录页面 as import_address

main -> add_member : 点击添加成员
main -> contact: 点击通讯录
add_member -> contact :1、填写人员信息 \n 2、点击保存

contact -> contact:获取成员列表

contact -> add_department:1、点击加号；  2、点击添加部门

contact -> import_address:1-点击批量导入/导出；2、文件导入

@enduml