- domain: .work.weixin.qq.com
  httpOnly: false
  name: wwrtx.cs_ind
  path: /
  secure: false
  value: ''
- domain: .work.weixin.qq.com
  httpOnly: false
  name: wwrtx.vid
  path: /
  secure: false
  value: '1688850571997254'
- domain: .work.weixin.qq.com
  httpOnly: false
  name: wxpay.vid
  path: /
  secure: false
  value: '1688850571997254'
- domain: .qq.com
  expiry: 2147385600
  httpOnly: false
  name: pgv_pvi
  path: /
  secure: false
  value: '2548114432'
- domain: .qq.com
  expiry: 2147385600
  httpOnly: false
  name: pgv_pvid
  path: /
  secure: false
  value: '5872691208'
- domain: .work.weixin.qq.com
  httpOnly: false
  name: wxpay.corpid
  path: /
  secure: false
  value: '1970325068449420'
- domain: .qq.com
  expiry: 1619700703
  httpOnly: false
  name: _gid
  path: /
  secure: false
  value: GA1.2.315260595.1619533500
- domain: .work.weixin.qq.com
  httpOnly: true
  name: wwrtx.sid
  path: /
  secure: false
  value: v0310RlBfbyTFVVP3C7E5Pvl8pqS5LQI0y0Ine188dXAfpbOizhanB-YjMn-ecsd
- domain: .work.weixin.qq.com
  httpOnly: false
  name: wwrtx.d2st
  path: /
  secure: false
  value: a7862079
- domain: .work.weixin.qq.com
  httpOnly: false
  name: Hm_lpvt_9364e629af24cb52acc78b43e8c9f77d
  path: /
  secure: false
  value: '1619614292'
- domain: .work.weixin.qq.com
  httpOnly: true
  name: wwrtx.refid
  path: /
  secure: false
  value: '4674277063091366'
- domain: work.weixin.qq.com
  expiry: 1619645827.111261
  httpOnly: true
  name: ww_rtkey
  path: /
  secure: false
  value: 2m0pjh2
- domain: .qq.com
  expiry: 1619875789
  httpOnly: false
  name: ptui_loginuin
  path: /
  secure: false
  value: '403505960'
- domain: .work.weixin.qq.com
  httpOnly: true
  name: wwrtx.vst
  path: /
  secure: false
  value: kY4lhLVxtQUU2MadpLZ-yi76_FkuIlO0lnFv8yHOFDTFz5D5k9ziTVTqHoJK4XkTVoXfNoseptzxiBbd8lot_eHcR4DtpR4zoXMBrNV5E16bph8mR7qzPVxCbShMRDTWcKOxKbGMvUtjtRS0I6lYwdZuR898tCZrIrFpbcgq1ZJrq0CpunuW-Vnh6WZW9wAVxsrFfT0oNGvdlyzlMhP7HXIesKEDMpDJIpWSLl9RJct0ze5JNRdD5pCVJqNxQA_x8R7qUIWDfmBC9GXCpbf6Ew
- domain: .work.weixin.qq.com
  expiry: 1651150291
  httpOnly: false
  name: Hm_lvt_9364e629af24cb52acc78b43e8c9f77d
  path: /
  secure: false
  value: 1619007918,1619533499,1619534322,1619614292
- domain: .qq.com
  expiry: 1909667441.177649
  httpOnly: false
  name: pac_uid
  path: /
  secure: false
  value: '1_403505960'
- domain: .qq.com
  expiry: 2147385600
  httpOnly: false
  name: o_cookie
  path: /
  secure: false
  value: '403505960'
- domain: .qq.com
  expiry: 2147483646.943188
  httpOnly: false
  name: ptcz
  path: /
  secure: false
  value: 224b72e3606a3a303ebaf01955bf0869f48fe63fba7fbffe642df7f500f4a054
- domain: .qq.com
  expiry: 2147483647.855961
  httpOnly: false
  name: RK
  path: /
  secure: false
  value: fKSYeDcW+o
- domain: .qq.com
  expiry: 1682686303
  httpOnly: false
  name: _ga
  path: /
  secure: false
  value: GA1.2.1801194509.1580695821
- domain: .work.weixin.qq.com
  expiry: 1622206305.906145
  httpOnly: false
  name: wwrtx.i18n_lan
  path: /
  secure: false
  value: zh
- domain: .work.weixin.qq.com
  httpOnly: true
  name: wwrtx.ltype
  path: /
  secure: false
  value: '1'
- domain: .work.weixin.qq.com
  httpOnly: true
  name: wwrtx.ref
  path: /
  secure: false
  value: direct
- domain: .work.weixin.qq.com
  expiry: 1650456140.297382
  httpOnly: false
  name: wwrtx.c_gdpr
  path: /
  secure: false
  value: '0'
- domain: .qq.com
  expiry: 1908442066
  httpOnly: false
  name: tvfe_boss_uuid
  path: /
  secure: false
  value: f680a6665e2d89e1
- domain: .qq.com
  expiry: 1619614352
  httpOnly: false
  name: _gat
  path: /
  secure: false
  value: '1'
